### ISSUE TITLE
It's possible to highlight more than 3 things on the character select screen

### ISSUE THREAD

**Issue by IsaacPD** [miishin/miipd#35] opened 2021-01-18 02:19 UTC
How to reproduce:

Click on more than 3 different "characters" on the character select scene

**Comment by miishin** [comment] 2021-01-18 05:29
pushed an almost fix in my branch - the issue is that buttons naturally come with the toggling when clicked behavior, so I think to properly fix this I'll have to turn that off.

**Comment by miishin** [comment] 2021-01-18 18:09
fixed in latest commit to pull request

**Closed by miishin** 2021-01-18 18:09 UTC
Labels: invalid
